global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'service-hello'
    static_configs:
      - targets: ['service-hello:8080', 'service-hello-sidecar:20000']

  - job_name: 'service-honk'
    static_configs:
      - targets: ['service-honk:8080', 'service-honk-sidecar:20000']
